--- #YAML:1.0
name:         Apache-GeoIP
version:      1.99
installdirs:  site
requires:
    Geo::IP:                     1.27 
license:      perl
abstract:     Look up country by IP address
authored_by:
    - Randy Kobes <randy.kobes@gmail.com>
distribution_type: module
no_index:
    file:
        - Apache2/t/response/TestGeoIP/ip.pm
        - Apache2/t/response/TestGeoIP/basic.pm
        - Apache2/t/response/TestGeoIP/mirror.pm
        - Apache2/t/response/TestGeoIP/name.pm
        - Apache/t/response/TestGeoIP/ip.pm
        - Apache/t/response/TestGeoIP/basic.pm
        - Apache/t/response/TestGeoIP/mirror.pm
        - Apache/t/response/TestGeoIP/name.pm
provides:
    Apache2::GeoIP:
        file: Apache2/GeoIP.pm
        version: 1.99
    Apache2::Geo::IP:
        file: Apache2/Geo/IP.pm
        version: 1.99
    Apache2::Geo::Mirror:
        file: Apache2/Geo/Mirror.pm
        version: 1.99
    Apache::GeoIP:
        file: Apache/GeoIP.pm
        version: 1.99
    Apache::Geo::IP:
        file: Apache/Geo/IP.pm
        version: 1.99
    Apache::Geo::Mirror:
        file: Apache/Geo/Mirror.pm
        version: 1.99

urls:
   license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
resources:
  license: http://dev.perl.org/licenses/
  homepage: http://github.com/rkobes/apache-geoip/tree/master
  repository: https://github.com/rkobes/apache-geoip
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Apache-GeoIP
  AnnoCPAN: http://annocpan.org/dist/Apache-GeoIP
  CPANForum: http://www.cpanforum.com/dist/Apache-GeoIP
  CPANTS: http://cpants.perl.org/dist/Apache-GeoIP
  Rating: http://cpanratings.perl.org/d/Apache-GeoIP
  SearchCPAN: http://search.cpan.org/~RKOBES/Apache-GeoIP/
  Testers: http://cpantesters.perl.org/show/Apache-GeoIP.html
  UWinnipeg: http://cpan.uwinnipeg.ca/dist/Apache-GeoIP
generated_by: Randy Kobes
